tkp-config:
  jwt:
    secret: soUicqC3yUtp0lq1st57RVt5g36048StY291PwPIMyI=
    expiration: 86400000

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/tkp
    username: tkp
    password: Abcd1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update
    show-sql: true


